spring:
  # datasource 数据源配置内容
  datasource:
    # 订单数据源配置
    order:
      jdbc-url: jdbc:mysql://10.0.99.213:3306/test_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: sg123456
    # 用户数据源配置
    user:
      jdbc-url: jdbc:mysql://10.0.99.213:3306/test_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: sg123456
  jpa:
    show-sql: true # 打印 SQL 。生产环境，建议关闭
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate:
      ddl-auto: none