###包括两部分的配置
###第一部分:多数据源测试
###第二部分:读写分离测试
spring:
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      primary: master # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 订单 orders 数据源配置
        order:
          url: jdbc:mysql://10.0.99.213:3306/test_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: admin
          password: sg123456
        # 用户 users 数据源配置
        user:
          url: jdbc:mysql://10.0.99.213:3306/test_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: admin
          password: sg123456

        ###读写分离
        master:
          url: jdbc:mysql://10.0.99.213:3306/test_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: admin
          password: sg123456

        slave_1:
          url: jdbc:mysql://10.0.99.213:3306/test_order1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: admin
          password: sg123456

        slave_2:
          url: jdbc:mysql://10.0.99.213:3306/test_order2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: admin
          password: sg123456

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.binge.baomidou.model # 配置数据库实体包路径
