spring:
  # ShardingSphere 配置项
  shardingsphere:
    datasource:
      # 所有数据源的名字
      names: ds-order, ds-user
      # 订单 orders 数据源配置
      ds-order:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.0.99.213:3306/test_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: admin
        password: sg123456
      # 订单 users 数据源配置
      ds-user:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.0.99.213:3306/test_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: admin
        password: sg123456
    # 分片规则
    sharding:
      tables:
        # orders 表配置
        t_order:
          actualDataNodes: ds-order.t_order # 映射到 ds-orders 数据源的 orders 表
        # users 表配置
        t_user:
          actualDataNodes: ds-user.t_user # 映射到 ds-users 数据源的 users 表

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.binge.shardingjdbc.model # 配置数据库实体包路径